DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS topics;

CREATE TABLE topics(
 id BIGSERIAL PRIMARY KEY,
 title VARCHAR(255) NOT NULl,
 description VARCHAR NOT NULL,
 url VARCHAR(255) NOT NULL
);

CREATE TABLE comments(
 id BIGSERIAL PRIMARY KEY,
 comment VARCHAR(500),
 voting INTEGER DEFAULT 0,
 topic_id INTEGER REFERENCES topics(id) NOT NULL
);


