DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS topics;

CREATE TABLE comments(
 id BIGSERIAL PRIMARY KEY,
 comment VARCHAR(500) NOT NULl,
 voting INTEGER NOT NULL,
 topic_id INTEGER NOT NULL
);

CREATE TABLE topics(
 id BIGSERIAL PRIMARY KEY,
 title VARCHAR(255) NOT NULl,
 description VARCHAR(255) NOT NULL,
 url VARCHAR(255) NOT NULL
);
